#!/bin/bash

if [ -d ./cpm ];
then
	echo './cpm already exist'
else
	mkdir cpm
fi

g++ ./Compiler/src/main.cpp ./Compiler/AST/ast_nodes.cpp ./Compiler/helpers/char_source.cpp ./Compiler/src/lexer.cpp ./Compiler/src/parser.cpp ./Compiler/src/compiler.cpp -std=c++17 -o cpm/cpm
